services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres_authDB
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      #- "5432:5432" 
      - "${POSTGRES_PORT}:5432" # Хостовый порт - ${POSTGRES_PORT}, внутренний - 5432
    networks:
      - network_auth  
    volumes:
      - ./.private/data/postgres:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/

networks:
  network_auth: